name: ericrie-se
static_sites:
  - name: web
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: _site
    environment_slug: node-js
    node_version: 20
